// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFf3XVRN3ErEVuzIKb2J3AvYrpNVch9WQ',
    appId: '1:776901487708:web:7af4bcf2e9c146b7b14a99',
    messagingSenderId: '776901487708',
    projectId: 'rateliving',
    authDomain: 'rateliving.firebaseapp.com',
    storageBucket: 'rateliving.firebasestorage.app',
    measurementId: 'G-PYBLTYRVG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkmiqTvcwqpI2YuTiFJf6oAii0CHIY5Vw',
    appId: '1:776901487708:android:c07d0d29ff76e4deb14a99',
    messagingSenderId: '776901487708',
    projectId: 'rateliving',
    storageBucket: 'rateliving.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFf3XVRN3ErEVuzIKb2J3AvYrpNVch9WQ',
    appId: '1:776901487708:web:3e0650f3ca9a9a27b14a99',
    messagingSenderId: '776901487708',
    projectId: 'rateliving',
    authDomain: 'rateliving.firebaseapp.com',
    storageBucket: 'rateliving.firebasestorage.app',
    measurementId: 'G-R7FHDJ8WB2',
  );
}
